### ISSUE TITLE
Changing asset metadata in grid breaks version

### ISSUE THREAD

**Issue by fashxp** [pimcore/studio-backend-bundle#603]
- Update asset metadata in grid
![Image](https://github.com/user-attachments/assets/9612969e-924c-4b7d-8138-da808aaf28e3)
- open asset detail and try to open just created version
![Image](https://github.com/user-attachments/assets/afff29ce-1c77-46df-b1e6-83c73fc81f59)

`
[2024-12-02T10:47:35.213352+00:00] app.ERROR: TypeError: Pimcore\Bundle\StudioBackendBundle\Version\Schema\CustomMetadataVersion::__construct(): Argument #2 ($language) must be of type string, null given, called in /var/www/html/vendor/pimcore/studio-backend-bundle/src/Version/Hydrator/CustomMetadataVersionHydrator.php on line 43 and defined in /var/www/html/vendor/pimcore/studio-backend-bundle/src/Version/Schema/CustomMetadataVersion.php:32 Stack trace: #0 /var/www/html/vendor/pimcore/studio-backend-bundle/src/Version/Hydrator/CustomMetadataVersionHydrator.php(43): Pimcore\Bundle\StudioBackendBundle\Version\Schema\CustomMetadataVersion->__construct('author', NULL, 'input', 'WikimediaImages...') #1 /var/www/html/vendor/pimcore/studio-backend-bundle/src/Version/Hydrator/CustomMetadataVersionHydrator.php(36): Pimcore\Bundle\StudioBackendBundle\Version\Hydrator\CustomMetadataVersionHydrator->hydrateSingle(Array) #2 [internal function]: Pimcore\Bundle\StudioBackendBundle\Version\Hydrator\CustomMetadataVersionHydrator->Pimcore\Bundle\StudioBackendBundle\Version\Hydrator\{closure}(Array) #3 /var/www/html/vendor/pimcore/studio-backend-bundle/src/Version/Hydrator/CustomMetadataVersionHydrator.php(35): array_map(Object(Closure), Array) #4 /var/www/html/vendor/pimcore/studio-backend-bundle/src/Version/Hydrator/AssetVersionHydrator.php(69): Pimcore\Bundle\StudioBackendBundle\Version\Hydrator\CustomMetadataVersionHydrator->hydrate(Array) #5 /var/www/html/vendor/pimcore/studio-backend-bundle/src/Version/Hydrator/AssetVersionHydrator.php(57): Pimcore\Bundle\StudioBackendBundle\Version\Hydrator\AssetVersionHydrator->hydrateAsset(Object(Pimcore\Model\Asset\Image)) #6 /var/www/html/vendor/pimcore/studio-backend-bundle/src/Version/Service/VersionDetailService.php(128): Pimcore\Bundle\StudioBackendBundle\Version\Hydrator\AssetVersionHydrator->hydrate(Object(Pimcore\Model\Asset\Image)) #7 /var/www/html/vendor/pimcore/studio-backend-bundle/src/Version/Service/VersionDetailService.php(58): Pimcore\Bundle\StudioBackendBundle\Version\Service\VersionDetailService->hydrate(Object(Pimcore\Model\Asset\Image), 'Pimcore\\Model\\A...') #8 /var/www/html/vendor/pimcore/studio-backend-bundle/src/Version/Controller/GetController.php(74): Pimcore\Bundle\StudioBackendBundle\Version\Service\VersionDetailService->getVersionData(50, Object(Pimcore\Model\User)) #9 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(181): Pimcore\Bundle\StudioBackendBundle\Version\Controller\GetController->getVersions(50) #10 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(76): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #11 /var/www/html/vendor/symfony/http-kernel/Kernel.php(197): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #12 /var/www/html/vendor/symfony/runtime/Runner/Symfony/HttpKernelRunner.php(35): Symfony\Component\HttpKernel\Kernel->handle(Object(Symfony\Component\HttpFoundation\Request)) #13 /var/www/html/vendor/autoload_runtime.php(29): Symfony\Component\Runtime\Runner\Symfony\HttpKernelRunner->run() #14 /var/www/html/public/index.php(20): require_once('/var/www/html/v...') #15 {main} [] []
 `

**Comment by markus-moser** [comment]
Currently the language needs to be a string, it should be optional/nullable

**Comment by mattamon** [comment]
@markus-moser https://github.com/pimcore/studio-backend-bundle/pull/604

I still do not get why we use tags like these `@pimcore-studio-backend-team`?
Nobody is getting notified - this is not a proper method get our attention :)

**Comment by markus-moser** [comment]
@mattamon This is not meant as a notificaton. It's just a hint that this comment is for you, I can also skip it if you prefer.

**Comment by markus-moser** [comment]
Now the comment looks like this:

![Image](https://github.com/user-attachments/assets/61362ef6-8a7e-4449-85fb-6a59e685261f)

The advantage before was that you can be sure that it's a comment for you and not a frontend internal one, this is the only reasen why I did this. ;)

**Comment by mattamon** [comment]
> Now the comment looks like this:
> 
> ![Image](https://github.com/user-attachments/assets/61362ef6-8a7e-4449-85fb-6a59e685261f)
> 
> The advantage before was that you can be sure that it's a comment for you and not a frontend internal one, this is the only reasen why I did this. ;)

I see, but since it is already in the backend bundle I think it is clear enough? :)

**Comment by markus-moser** [comment]
In this case yes, but it was in the frontend repo before and I moved it... Sometimes we can jump around between the different teams and therefore I used this notation sometimes in the past to give a bit of attention to the relevant comment so that you don't need to read everything in detail. But at the end it's just the list in your backlog (or board of the galaxy) which is relevant as it's not possible to notify teams (and also not needed, the backlog approach is fine, most of the time there is no need for immediate action).

**Comment by markus-moser** [comment]
@fashxp Could you please re-try if it works now after updating the backend bundle?

**Comment by mattamon** [comment]
> In this case yes, but it was in the frontend repo before and I moved it... Sometimes we can jump around between the different teams and therefore I used this notation sometimes in the past to give a bit of attention to the relevant comment so that you don't need to read everything in detail. But at the end it's just the list in your backlog (or board of the galaxy) which is relevant as it's not possible to notify teams (and also not needed, the backlog approach is fine, most of the time there is no need for immediate action).

I get the intention, but since we never get notified that there is a comment in the first place, it would only help if we would constantly scan the repo for comments, that contain this tag :)

**Comment by fashxp** [comment]
looks good  now 👍  thx
