### ISSUE TITLE
Opening data objects of type News fails

### ISSUE THREAD

**Issue by fashxp** [pimcore/studio-backend-bundle#608]
[2024-12-02T11:07:48.981042+00:00] request.CRITICAL: Uncaught PHP Exception TypeError: "Pimcore\Bundle\StudioBackendBundle\DataObject\Service\DataService::getNormalizedValue(): Argument pimcore/studio-ui-bundle#2 ($fieldDefinition) must be of type Pimcore\Model\DataObject\ClassDefinition\Data, null given, called in /var/www/html/vendor/pimcore/studio-backend-bundle/src/DataObject/Data/Adapter/LocalizedFieldsAdapter.php on line 130" at DataService.php line 82 {"exception":"[object] (TypeError(code: 0): Pimcore\\Bundle\\StudioBackendBundle\\DataObject\\Service\\DataService::getNormalizedValue(): Argument pimcore/studio-ui-bundle#2 ($fieldDefinition) must be of type Pimcore\\Model\\DataObject\\ClassDefinition\\Data, null given, called in /var/www/html/vendor/pimcore/studio-backend-bundle/src/DataObject/Data/Adapter/LocalizedFieldsAdapter.php on line 130 at /var/www/html/vendor/pimcore/studio-backend-bundle/src/DataObject/Service/DataService.php:82)"} []
[2024-12-02T11:07:48.981389+00:00] app.ERROR: TypeError: Pimcore\Bundle\StudioBackendBundle\DataObject\Service\DataService::getNormalizedValue(): Argument pimcore/studio-ui-bundle#2 ($fieldDefinition) must be of type Pimcore\Model\DataObject\ClassDefinition\Data, null given, called in /var/www/html/vendor/pimcore/studio-backend-bundle/src/DataObject/Data/Adapter/LocalizedFieldsAdapter.php on line 130 and defined in /var/www/html/vendor/pimcore/studio-backend-bundle/src/DataObject/Service/DataService.php:82 Stack trace: #0 /var/www/html/vendor/pimcore/studio-backend-bundle/src/DataObject/Data/Adapter/LocalizedFieldsAdapter.php(130): Pimcore\Bundle\StudioBackendBundle\DataObject\Service\DataService->getNormalizedValue('<p>Lorem ipsum ...', NULL) pimcore/studio-ui-bundle#1 /var/www/html/vendor/pimcore/studio-backend-bundle/src/DataObject/Service/DataService.php(92): Pimcore\Bundle\StudioBackendBundle\DataObject\Data\Adapter\LocalizedFieldsAdapter->normalize(Object(Pimcore\Model\DataObject\Localizedfield), NULL) pimcore/studio-ui-bundle#2 /var/www/html/vendor/pimcore/studio-backend-bundle/src/DataObject/Data/Adapter/FieldCollectionsAdapter.php(113): Pimcore\Bundle\StudioBackendBundle\DataObject\Service\DataService->getNormalizedValue(Object(Pimcore\Model\DataObject\Localizedfield), Object(Pimcore\Model\DataObject\ClassDefinition\Data\Localizedfields)) pimcore/studio-ui-bundle#3 /var/www/html/vendor/pimcore/studio-backend-bundle/src/DataObject/Service/DataService.php(92): Pimcore\Bundle\StudioBackendBundle\DataObject\Data\Adapter\FieldCollectionsAdapter->normalize(Object(Pimcore\Model\DataObject\Localizedfield), Object(Pimcore\Model\DataObject\ClassDefinition\Data\Fieldcollections)) pimcore/studio-ui-bundle#4 /var/www/html/vendor/pimcore/studio-backend-bundle/src/DataObject/Service/DataService.php(57): Pimcore\Bundle\StudioBackendBundle\DataObject\Service\DataService->getNormalizedValue(Object(Pimcore\Model\DataObject\Fieldcollection), Object(Pimcore\Model\DataObject\ClassDefinition\Data\Fieldcollections)) pimcore/studio-ui-bundle#5 /var/www/html/vendor/pimcore/studio-backend-bundle/src/DataObject/Service/DataObjectService.php(358): Pimcore\Bundle\StudioBackendBundle\DataObject\Service\DataService->getObjectData(Object(Pimcore\Model\DataObject\News)) pimcore/studio-ui-bundle#6 /var/www/html/vendor/pimcore/studio-backend-bundle/src/DataObject/Service/DataObjectService.php(160): Pimcore\Bundle\StudioBackendBundle\DataObject\Service\DataObjectService->setObjectDetailData(Object(Pimcore\Bundle\StudioBackendBundle\DataObject\Schema\DataObject)) pimcore/studio-ui-bundle#7 /var/www/html/vendor/pimcore/studio-backend-bundle/src/DataObject/Controller/GetController.php(71): Pimcore\Bundle\StudioBackendBundle\DataObject\Service\DataObjectService->getDataObject(772) pimcore/studio-ui-bundle#8 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(181): Pimcore\Bundle\StudioBackendBundle\DataObject\Controller\GetController->getDataObjectById(772) pimcore/studio-ui-bundle#9 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(76): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) pimcore/studio-ui-bundle#10 /var/www/html/vendor/symfony/http-kernel/Kernel.php(197): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) pimcore/studio-ui-bundle#11 /var/www/html/vendor/symfony/runtime/Runner/Symfony/HttpKernelRunner.php(35): Symfony\Component\HttpKernel\Kernel->handle(Object(Symfony\Component\HttpFoundation\Request)) pimcore/studio-ui-bundle#12 /var/www/html/vendor/autoload_runtime.php(29): Symfony\Component\Runtime\Runner\Symfony\HttpKernelRunner->run() pimcore/studio-ui-bundle#13 /var/www/html/public/index.php(20): require_once('/var/www/html/v...') pimcore/studio-ui-bundle#14 {main} [] []
[2024-12-02T11:07:48.991675+00:00] app.EMERGENCY: Unable to render error page, exception thrown [] []
[2024-12-02T11:07:48.991807+00:00] app.EMERGENCY: Twig\Error\LoaderError: Unable to find template "" (looked into: /var/www/html/templates, /var/www/html/vendor/symfony/twig-bridge/Resources/views/Form). in /var/www/html/vendor/twig/twig/src/Loader/FilesystemLoader.php:234 Stack trace: #0 /var/www/html/vendor/twig/twig/src/Loader/FilesystemLoader.php(138): Twig\Loader\FilesystemLoader->findTemplate('') pimcore/studio-ui-bundle#1 /var/www/html/vendor/twig/twig/src/Environment.php(304): Twig\Loader\FilesystemLoader->getCacheKey('') pimcore/studio-ui-bundle#2 /var/www/html/vendor/twig/twig/src/Environment.php(357): Twig\Environment->getTemplateClass('') pimcore/studio-ui-bundle#3 /var/www/html/vendor/twig/twig/src/Environment.php(320): Twig\Environment->load('') pimcore/studio-ui-bundle#4 /var/www/html/vendor/pimcore/pimcore/bundles/CoreBundle/src/EventListener/Frontend/ContentTemplateListener.php(90): Twig\Environment->render('', Array) pimcore/studio-ui-bundle#5 /var/www/html/vendor/symfony/event-dispatcher/EventDispatcher.php(260): Pimcore\Bundle\CoreBundle\EventListener\Frontend\ContentTemplateListener->onKernelView(Object(Symfony\Component\HttpKernel\Event\ViewEvent), 'kernel.view', Object(Symfony\Component\EventDispatcher\EventDispatcher)) pimcore/studio-ui-bundle#6 /var/www/html/vendor/symfony/event-dispatcher/EventDispatcher.php(220): Symfony\Component\EventDispatcher\EventDispatcher::Symfony\Component\EventDispatcher\{closure}(Object(Symfony\Component\HttpKernel\Event\ViewEvent), 'kernel.view', Object(Symfony\Component\EventDispatcher\EventDispatcher)) pimcore/studio-ui-bundle#7 /var/www/html/vendor/symfony/event-dispatcher/EventDispatcher.php(56): Symfony\Component\EventDispatcher\EventDispatcher->callListeners(Array, 'kernel.view', Object(Symfony\Component\HttpKernel\Event\ViewEvent)) pimcore/studio-ui-bundle#8 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(186): Symfony\Component\EventDispatcher\EventDispatcher->dispatch(Object(Symfony\Component\HttpKernel\Event\ViewEvent), 'kernel.view') pimcore/studio-ui-bundle#9 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(76): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 2) pimcore/studio-ui-bundle#10 /var/www/html/vendor/symfony/http-kernel/HttpCache/SubRequestHandler.php(86): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 2, false) pimcore/studio-ui-bundle#11 /var/www/html/vendor/symfony/http-kernel/Fragment/InlineFragmentRenderer.php(78): Symfony\Component\HttpKernel\HttpCache\SubRequestHandler::handle(Object(Symfony\Component\HttpKernel\HttpKernel), Object(Symfony\Component\HttpFoundation\Request), 2, false) pimcore/studio-ui-bundle#12 /var/www/html/vendor/pimcore/pimcore/lib/Document/Renderer/DocumentRenderer.php(121): Symfony\Component\HttpKernel\Fragment\InlineFragmentRenderer->render('/_fragment?_pat...', Object(Symfony\Component\HttpFoundation\Request), Array) pimcore/studio-ui-bundle#13 /var/www/html/vendor/pimcore/pimcore/bundles/CoreBundle/src/EventListener/ResponseExceptionListener.php(117): Pimcore\Document\Renderer\DocumentRenderer->render(Object(Pimcore\Bundle\PersonalizationBundle\Model\Document\Page), Array) pimcore/studio-ui-bundle#14 /var/www/html/vendor/pimcore/pimcore/bundles/CoreBundle/src/EventListener/ResponseExceptionListener.php(77): Pimcore\Bundle\CoreBundle\EventListener\ResponseExceptionListener->handleErrorPage(Object(Symfony\Component\HttpKernel\Event\ExceptionEvent)) pimcore/studio-ui-bundle#15 /var/www/html/vendor/symfony/event-dispatcher/EventDispatcher.php(260): Pimcore\Bundle\CoreBundle\EventListener\ResponseExceptionListener->onKernelException(Object(Symfony\Component\HttpKernel\Event\ExceptionEvent), 'kernel.exceptio...', Object(Symfony\Component\EventDispatcher\EventDispatcher)) pimcore/studio-ui-bundle#16 /var/www/html/vendor/symfony/event-dispatcher/EventDispatcher.php(220): Symfony\Component\EventDispatcher\EventDispatcher::Symfony\Component\EventDispatcher\{closure}(Object(Symfony\Component\HttpKernel\Event\ExceptionEvent), 'kernel.exceptio...', Object(Symfony\Component\EventDispatcher\EventDispatcher)) pimcore/studio-ui-bundle#17 /var/www/html/vendor/symfony/event-dispatcher/EventDispatcher.php(56): Symfony\Component\EventDispatcher\EventDispatcher->callListeners(Array, 'kernel.exceptio...', Object(Symfony\Component\HttpKernel\Event\ExceptionEvent)) pimcore/studio-ui-bundle#18 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(239): Symfony\Component\EventDispatcher\EventDispatcher->dispatch(Object(Symfony\Component\HttpKernel\Event\ExceptionEvent), 'kernel.exceptio...') pimcore/studio-ui-bundle#19 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(132): Symfony\Component\HttpKernel\HttpKernel->handleThrowable(Object(TypeError), Object(Symfony\Component\HttpFoundation\Request), 1) pimcore/studio-ui-bundle#20 /var/www/html/vendor/symfony/http-kernel/EventListener/DebugHandlersListener.php(84): Symfony\Component\HttpKernel\HttpKernel->terminateWithException(Object(TypeError), Object(Symfony\Component\HttpFoundation\Request)) pimcore/studio-ui-bundle#21 /var/www/html/vendor/symfony/error-handler/ErrorHandler.php(538): Symfony\Component\HttpKernel\EventListener\DebugHandlersListener::Symfony\Component\HttpKernel\EventListener\{closure}(Object(TypeError)) pimcore/studio-ui-bundle#22 [internal function]: Symfony\Component\ErrorHandler\ErrorHandler->handleException(Object(TypeError)) pimcore/studio-ui-bundle#23 {main} [] []

**Comment by martineiber** [comment]
@fashxp Should be fixed with https://github.com/pimcore/studio-backend-bundle/pull/609

**Comment by fashxp** [comment]
works now
